{% set version = "1.7.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gtsummary
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gtsummary_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gtsummary/gtsummary_{{ version }}.tar.gz
  sha256: 73ed05c4b7c62f3e5e7bb86c940d4a03d6b39f420a3582039a725b367a6336d0

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-broom >=1.0.1
    - r-broom.helpers >=1.10.0
    - r-cli >=3.1.1
    - r-dplyr >=1.0.7
    - r-forcats >=0.5.1
    - r-glue >=1.6.0
    - r-gt >=0.8.0
    - r-knitr >=1.37
    - r-lifecycle >=1.0.1
    - r-purrr >=0.3.4
    - r-rlang >=1.0.3
    - r-stringr >=1.4.0
    - r-tibble >=3.1.6
    - r-tidyr >=1.1.4
  run:
    - r-base
    - r-broom >=1.0.1
    - r-broom.helpers >=1.10.0
    - r-cli >=3.1.1
    - r-dplyr >=1.0.7
    - r-forcats >=0.5.1
    - r-glue >=1.6.0
    - r-gt >=0.8.0
    - r-knitr >=1.37
    - r-lifecycle >=1.0.1
    - r-purrr >=0.3.4
    - r-rlang >=1.0.3
    - r-stringr >=1.4.0
    - r-tibble >=3.1.6
    - r-tidyr >=1.1.4

test:
  requires:
    - r-testthat
    - r-ggstats
    - r-huxtable >=5.4.0
    - r-openxlsx
  commands:
    - $R -e "library('gtsummary')"                          # [not win]
    - $R -e "testthat::test_package('gtsummary')"           # [not win]
    - "\"%R%\" -e \"library('gtsummary')\""                 # [win]
    - "\"%R%\" -e \"testthat::test_package('gtsummary')\""  # [win]

about:
  home: https://www.danieldsjoberg.com/gtsummary/
  dev_url: https://github.com/ddsjoberg/gtsummary
  doc_url: https://www.danieldsjoberg.com/gtsummary/reference/
  license: MIT
  summary: Creates presentation-ready tables summarizing data sets, regression models, and more. The code to create the tables is concise and highly customizable. Data frames can be summarized with any function, e.g. mean(), median(), even user-written functions. Regression models are summarized and include the reference
    rows for categorical variables. Common regression models, such as logistic regression and Cox proportional hazards regression, are automatically identified and the tables are pre-filled with appropriate column headers.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler
