{% set version = "2.0.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gtsummary
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gtsummary_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gtsummary/gtsummary_{{ version }}.tar.gz
  sha256: d5a3fc2812224688d0eb4c48555ee62cf0163d888b45736c8c0d5bbaf96f066f

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cards >=0.2.2
    - r-cli >=3.6.1
    - r-dplyr >=1.1.3
    - r-glue >=1.6.2
    - r-gt >=0.10.0
    - r-lifecycle >=1.0.3
    - r-rlang >=1.1.1
    - r-tidyr >=1.3.0
    - r-vctrs
  run:
    - r-base
    - r-cards >=0.2.2
    - r-cli >=3.6.1
    - r-dplyr >=1.1.3
    - r-glue >=1.6.2
    - r-gt >=0.10.0
    - r-lifecycle >=1.0.3
    - r-rlang >=1.1.1
    - r-tidyr >=1.3.0
    - r-vctrs

test:
  requires:
    - r-testthat >=3.2.0
    - r-huxtable >=5.4.0
    - r-broom >= 1.0.5
    - r-broom.helpers >=1.17.0
    - r-broom.mixed >=0.2.9
    - r-survival
    - r-cardx >=0.2.1
    - r-survey >=4.2
    - r-smd >=0.6.6
    - r-car >=3.0-11
    - r-parameters >=0.20.2
    - r-emmeans >=1.7.3
  commands:
    - $R -e "library('gtsummary')"                          # [not win]
    - $R -e "testthat::test_package('gtsummary')"           # [not win]
    - "\"%R%\" -e \"library('gtsummary')\""                 # [win]
    - "\"%R%\" -e \"testthat::test_package('gtsummary')\""  # [win]

about:
  home: https://www.danieldsjoberg.com/gtsummary/
  dev_url: https://github.com/ddsjoberg/gtsummary
  doc_url: https://www.danieldsjoberg.com/gtsummary/reference/
  license: MIT
  summary: Creates presentation-ready tables summarizing data sets, regression models, and more. The code to create the tables is concise and highly customizable. Data frames can be summarized with any function, e.g. mean(), median(), even user-written functions. Regression models are summarized and include the reference
    rows for categorical variables. Common regression models, such as logistic regression and Cox proportional hazards regression, are automatically identified and the tables are pre-filled with appropriate column headers.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
